import React from "react";
import "../index.css"; // Import the CSS file for this component

const Season = () => {
  return (
    
    <div>
    
      <h1 className="gold">See how The Comets are getting on!</h1>
      
      <h2 className="blu2">2023 League Table</h2>
      <table className="league-table">
        
  <thead>
    <tr>
      <th>Team</th>
      <th>Played</th>
      <th>Won</th>
      <th>Drawn</th>
      <th>Lost</th>
      <th>Goals For</th>
      <th>Goals Against</th>
      <th>Goal Difference</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Independiente</td>
      <td>27</td>
      <td>17</td>
      <td>6</td>
      <td>4</td>
      <td>50</td>
      <td>29</td>
      <td>31</td>
      <td>57</td>
    </tr>
    <tr>
      <td>Talleres</td>
      <td>27</td>
      <td>16</td>
      <td>7</td>
      <td>4</td>
      <td>44</td>
      <td>26</td>
      <td>18</td>
      <td>55</td>
    </tr>
    <tr>
      <td>Racing Club</td>
      <td>27</td>
      <td>16</td>
      <td>7</td>
      <td>4</td>
      <td>50</td>
      <td>28</td>
      <td>22</td>
      <td>54</td>
    </tr>
    <tr>
      <td>Boca Juniors</td>
      <td>27</td>
      <td>15</td>
      <td>9</td>
      <td>3</td>
      <td>54</td>
      <td>33</td>
      <td>21</td>
      <td>54</td>
    </tr>
    <tr>
      <td>Lanùs</td>
      <td>27</td>
      <td>15</td>
      <td>6</td>
      <td>6</td>
      <td>43</td>
      <td>29</td>
      <td>14</td>
      <td>51</td>
    </tr>
    <tr>
      <td>ESTRELLA RÍO CUARTO</td>
      <td>27</td>
      <td>15</td>
      <td>5</td>
      <td>7</td>
      <td>58</td>
      <td>39</td>
      <td>19</td>
      <td>50</td>
    </tr>
    <tr>
      <td>River Plate</td>
      <td>27</td>
      <td>14</td>
      <td>8</td>
      <td>5</td>
      <td>47</td>
      <td>28</td>
      <td>19</td>
      <td>50</td>
    </tr>
    <tr>
      <td>Argentinos Jrs.</td>
      <td>27</td>
      <td>14</td>
      <td>8</td>
      <td>5</td>
      <td>42</td>
      <td>31</td>
      <td>11</td>
      <td>50</td>
    </tr>
    <tr>
      <td>Vélez Sarsfield</td>
      <td>27</td>
      <td>11</td>
      <td>8</td>
      <td>8</td>
      <td>37</td>
      <td>27</td>
      <td>10</td>
      <td>41</td>
    </tr>
    <tr>
      <td>Huracán</td>
      <td>27</td>
      <td>12</td>
      <td>3</td>
      <td>12</td>
      <td>43</td>
      <td>35</td>
      <td>8</td>
      <td>39</td>
    </tr>
    <tr>
      <td>Estudiantes</td>
      <td>27</td>
      <td>9</td>
      <td>11</td>
      <td>7</td>
      <td>37</td>
      <td>29</td>
      <td>8</td>
      <td>38</td>
    </tr>
    <tr>
      <td>Newell's Old Boys</td>
      <td>27</td>
      <td>11</td>
      <td>5</td>
      <td>11</td>
      <td>31</td>
      <td>33</td>
      <td>-2</td>
      <td>38</td>
    </tr>
    <tr>
      <td>San Lorenzo</td>
      <td>27</td>
      <td>8</td>
      <td>12</td>
      <td>7</td>
      <td>37</td>
      <td>33</td>
      <td>4</td>
      <td>36</td>
    </tr>
    <tr>
      <td>Defensa</td>
      <td>27</td>
      <td>9</td>
      <td>9</td>
      <td>9</td>
      <td>37</td>
      <td>34</td>
      <td>3</td>
      <td>36</td>
    </tr>
    <tr>
      <td>Rosario Central</td>
      <td>27</td>
      <td>8</td>
      <td>12</td>
      <td>7</td>
      <td>30</td>
      <td>34</td>
      <td>-4</td>
      <td>36</td>
    </tr>
    <tr>
      <td>Banfield</td>
      <td>27</td>
      <td>8</td>
      <td>10</td>
      <td>9</td>
      <td>30</td>
      <td>-37</td>
      <td>-7</td>
      <td>34</td>
    </tr>
    <tr>
      <td>Sarmiento</td>
      <td>27</td>
      <td>7</td>
      <td>9</td>
      <td>11</td>
      <td>31</td>
      <td>37</td>
      <td>-6</td>
      <td>30</td>
    </tr>
    <tr>
      <td>Colón</td>
      <td>27</td>
      <td>7</td>
      <td>9</td>
      <td>11</td>
      <td>30</td>
      <td>37</td>
      <td>-7</td>
      <td>30</td>
    </tr>
    <tr>
      <td>Tigre</td>
      <td>27</td>
      <td>5</td>
      <td>14</td>
      <td>8</td>
      <td>29</td>
      <td>35</td>
      <td>-6</td>
      <td>29</td>
    </tr>
    <tr>
      <td>Patronato</td>
      <td>27</td>
      <td>8</td>
      <td>5</td>
      <td>14</td>
      <td>31</td>
      <td>45</td>
      <td>-14</td>
      <td>29</td>
    </tr>
    <tr>
      <td>Unión</td>
      <td>27</td>
      <td>7</td>
      <td>7</td>
      <td>13</td>
      <td>27</td>
      <td>40</td>
      <td>-13</td>
      <td>28</td>
    </tr>
    <tr>
      <td>Central Córdoba</td>
      <td>27</td>
      <td>6</td>
      <td>9</td>
      <td>12</td>
      <td>34</td>
      <td>42</td>
      <td>-8</td>
      <td>27</td>
    </tr>
    <tr>
      <td>Gimnasia</td>
      <td>27</td>
      <td>6</td>
      <td>9</td>
      <td>12</td>
      <td>28</td>
      <td>38</td>
      <td>-10</td>
      <td>27</td>
    </tr>
    <tr>
      <td>Arsenal</td>
      <td>27</td>
      <td>6</td>
      <td>9</td>
      <td>12</td>
      <td>24</td>
      <td>34</td>
      <td>-10</td>
      <td>27</td>
    </tr>
    <tr>
      <td>Platense</td>
      <td>27</td>
      <td>5</td>
      <td>7</td>
      <td>15</td>
      <td>25</td>
      <td>43</td>
      <td>-18</td>
      <td>22</td>
    </tr>
    <tr>
      <td>Barracas Central</td>
      <td>27</td>
      <td>5</td>
      <td>6</td>
      <td>16</td>
      <td>20</td>
      <td>42</td>
      <td>-22</td>
      <td>21</td>
    </tr>
    <tr>
      <td>Atlético Tucumán</td>
      <td>27</td>
      <td>5</td>
      <td>4</td>
      <td>18</td>
      <td>26</td>
      <td>48</td>
      <td>-22</td>
      <td>19</td>
    </tr>
    <tr>
      <td>Aldosivi</td>
      <td>27</td>
      <td>4</td>
      <td>4</td>
      <td>19</td>
      <td>32</td>
      <td>61</td>
      <td>-29</td>
      <td>19</td>
    </tr>
  </tbody>
</table>
<section>
  <h2 className="blu2">Copa De Primera</h2>
</section>
<table className="league-table">
  <thead>
    <tr>
      <th>Team</th>
      <th>Played</th>
      <th>Won</th>
      <th>Drawn</th>
      <th>Lost</th>
      <th>Goals For</th>
      <th>Goals Against</th>
      <th>Points</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td>ESTRELLA RÍO CUARTO</td>
      <td>13</td>
      <td>10</td>
      <td>2</td>
      <td>1</td>
      <td>38</td>
      <td>21</td>
      <td>32</td>
    </tr>
    <tr>
      <td>Racing Club</td>
      <td>13</td>
      <td>8</td>
      <td>4</td>
      <td>0</td>
      <td>30</td>
      <td>10</td>
      <td>28</td>
    </tr>
    <tr>
      <td>San Lorenzo</td>
      <td>13</td>
      <td>7</td>
      <td>4</td>
      <td>2</td>
      <td>22</td>
      <td>14</td>
      <td>25</td>
    </tr>
    <tr>
      <td>Lanùs</td>
      <td>13</td>
      <td>7</td>
      <td>3</td>
      <td>3</td>
      <td>22</td>
      <td>16</td>
      <td>24</td>
    </tr>
    <tr>
      <td>Talleres</td>
      <td>13</td>
      <td>6</td>
      <td>5</td>
      <td>2</td>
      <td>18</td>
      <td>13</td>
      <td>23</td>
    </tr>
    <tr>
      <td>Tigre</td>
      <td>13</td>
      <td>7</td>
      <td>2</td>
      <td>4</td>
      <td>18</td>
      <td>17</td>
      <td>23</td>
    </tr>
    <tr>
      <td>Atlético Tucumán</td>
      <td>13</td>
      <td>4</td>
      <td>3</td>
      <td>6</td>
      <td>15</td>
      <td>23</td>
      <td>15</td>
    </tr>
    <tr>
      <td>Colón</td>
      <td>13</td>
      <td>3</td>
      <td>5</td>
      <td>5</td>
      <td>14</td>
      <td>16</td>
      <td>14</td>
    </tr>
    <tr>
      <td>Arsenal</td>
      <td>13</td>
      <td>3</td>
      <td>5</td>
      <td>5</td>
      <td>15</td>
      <td>19</td>
      <td>14</td>
    </tr>
    <tr>
      <td>Estudiantes</td>
      <td>13</td>
      <td>4</td>
      <td>2</td>
      <td>7</td>
      <td>16</td>
      <td>21</td>
      <td>14</td>
    </tr>
    <tr>
      <td>Huracán</td>
      <td>13</td>
      <td>3</td>
      <td>4</td>
      <td>5</td>
      <td>16</td>
      <td>17</td>
      <td>13</td>
    </tr>
    <tr>
      <td>Banfield</td>
      <td>13</td>
      <td>3</td>
      <td>2</td>
      <td>8</td>
      <td>12</td>
      <td>23</td>
      <td>11</td>
    </tr>
    <tr>
      <td>Central Córdoba</td>
      <td>13</td>
      <td>1</td>
      <td>5</td>
      <td>7</td>
      <td>15</td>
      <td>24</td>
      <td>8</td>
    </tr>
    <tr>
      <td>Patronato</td>
      <td>13</td>
      <td>0</td>
      <td>2</td>
      <td>11</td>
      <td>11</td>
      <td>28</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
    </div>
  );
};

export default Season;
